#! /usr/bin/env bash

# globals
INSTALL_REPO='dnf --nogpgcheck install -y'
INSTALL_PKG='dnf install -y'
PACKAGE_LIST=(
    rpmfusion-free-release-tainted
    brasero
    clamav
    clamav-update
    ctags
    dconf-editor
    deja-dup
    emacs    
    encfs
    epson-inkjet-printer-escpr
    exiv2
    filezilla
    gimp
    google-chrome-stable
    gnome-tweak-tool
    gparted
    gstreamer-plugins-*
    gstreamer1-plugins-*
    gthumb
    htop
    inkscape
    keepassx
    labyrinth
    libdvdcss
    libdvdnav
    libdvdread
    libvirt
    livecd-tools
    liveusb-creator
    mozilla-adblockplus
    mozilla-noscript
    mozilla-https-everywhere
    mplayer
    ncurses-devel
    openssl-devel
    pdfgrep    
    rapid-photo-downloader
    simple-scan
    shotwell
    sshfs
    tintin
    tintin-doc
    tmux
    tracker-preferences
    transmission
    unrar
    unzip
    uuid
    virt-manager
    vlc
    vagrant
)

function main {
    verify_if_running_as_root
    update_distro
    add_repositories
    install_packages
}

function verify_if_running_as_root {
    if (( $EUID != 0 )); then
        echo "${0##*/}: Please run the script as root."
        exit
    fi
}

function update_distro {
    dnf update -y
}
    
function add_repositories {
    # rpmfusion-free repo
    $INSTALL_REPO http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-stable.noarch.rpm

    # rpmfusion-nonfree repo
    $INSTALL_REPO http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-stable.noarch.rpm

    # rpmfusion-nonfree 
    
    # microsoft vs code
    rpm --import https://packages.microsoft.com/keys/microsoft.asc
    sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'

    # google chrome repo
    cat << EOF > /etc/yum.repos.d/google-chrome.repo
[google-chrome]
name=google-chrome - \$basearch
baseurl=http://dl.google.com/linux/chrome/rpm/stable/\$basearch
enabled=1
gpgcheck=1
gpgkey=https://dl-ssl.google.com/linux/linux_signing_key.pub
EOF

}
    
function install_packages {
    for p in "${PACKAGE_LIST[@]}"
    do
        $INSTALL_PKG $p
    done
}


# execute script
main
