#!/usr/bin/bash

# check if running as root
if (( $EUID != 0 )); then
    echo "${0##*/}: Please run the script as root. Exiting..."
    exit
fi

# update the system
apt update && apt upgrade -y

# change login shell
chsh -s /usr/bin/bash $USER

# install programs
apt install -y emacs tmux ufw

# create folder structure
mkdir -p $HOME/workspace/repos/local
mkdir -p $HOME/workspace/repos/local/notes
mkdir -p $HOME/workspace/repos/github/neffercarrillo

# download dotfiles
cd $HOME/workspace/repos/github/neffercarrillo/
git https://github.com/neffercarrillo/dotfiles.git
cd dotfiles
bash setup

# create ssh keys
ssh-keygen -t ecdsa -b 521

# turn on firewall
ufw logging on
ufw enable

# configure emacs server
systemctl --user enable --now emacs